# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojwpADigWFRf6UoHXnQzZ9Taa6xxLu3z
"""

! pip install streamlit -q

! pip install transformers datasets

! sudo apt install tesseract-ocr
! pip install pytesseract

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

